# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'projeto-mvvm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for projeto-mvvm
	pod 'lottie-ios', '~> 3.1'
end
